name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore Dependencies
        run: dotnet restore backend/TravelWiseAPI.sln

      - name: Build Project
        run: dotnet build backend/TravelWiseAPI.sln --configuration Release

      - name: Publish API
        run: dotnet publish backend/TravelWiseAPI.sln -c Release -o backend/publish

      - name: Deploy to Render
        uses: jakejarvis/render-deploy@v1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
