name: Build and Deploy to Windows VM

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    outputs:
      tag: ${{ steps.date.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Generate tag
        id: date
        shell: pwsh
        run: |
          echo "tag=$([int]((Get-Date).ToUniversalTime() - [datetime]'1970-01-01').TotalSeconds)" >> $env:GITHUB_OUTPUT

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/frontend:${{ steps.date.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend:${{ steps.date.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/backend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to app directory
        shell: powershell
        run: |
          New-Item -Path C:\app -ItemType Directory -Force
          Copy-Item -Path .\docker-compose.yml -Destination C:\app\ -Force
          Copy-Item -Path .\database -Destination C:\app\ -Recurse -Force

      - name: Deploy with Docker Compose
        shell: powershell
        run: |
          Set-Location C:\app
          $env:TAG="${{ needs.build-and-push.outputs.tag }}"
          docker-compose pull
          docker-compose up -d
          docker system prune -f
